import { readFileSync, writeFileSync } from 'node:fs';
import {
  actionNames,
  themes,
  colors,
  icons,
  makeDefaultState,
  PadSchema,
} from '../shared/model.js';

const pkg = JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf8'));
const lock = JSON.parse(readFileSync(new URL('../package-lock.json', import.meta.url), 'utf8'));
const defaults = makeDefaultState();
const cell = (value: unknown) => String(value).replaceAll('|', '\\|').replaceAll('\n', ' ');
const rows = (values: unknown[][]) =>
  values.map((row) => `| ${row.map(cell).join(' | ')} |`).join('\n');
const content = `# Generated project reference

<!-- Generated by scripts/generate-reference.ts. Do not edit manually. -->

Run \`npm run docs:generate\` after changing package metadata, commands, dependencies, or shared choices/defaults. \`npm run docs:check\` verifies this file matches its sources.

## App identity

| Property | Value |
| --- | --- |
${rows([
  ['Version', pkg.version],
  ['Product', pkg.build.productName],
  ['Bundle / application ID', pkg.build.appId],
  ['State schema version', defaults.schemaVersion],
])}

## Commands

| npm script | Runs |
| --- | --- |
${rows(Object.entries(pkg.scripts).map(([name, command]) => [name, `\`${command}\``]))}

## Actions

| Stored type | UI label |
| --- | --- |
${rows(Object.entries(actionNames))}

## Defaults and choices

| Item | Value |
| --- | --- |
${rows([
  ['Shortcut', defaults.settings.shortcut],
  ['Hide after action', defaults.settings.hideAfterAction],
  ['Launch at login', defaults.settings.launchAtLogin],
  ['Starter active pad', defaults.activePadId],
  ['Starter layout', `${defaults.pads[0].columns} columns × ${defaults.pads[0].rows} rows`],
  ['Column limits', `${PadSchema.shape.columns.minValue}–${PadSchema.shape.columns.maxValue}`],
  ['Row limits', `${PadSchema.shape.rows.minValue}–${PadSchema.shape.rows.maxValue}`],
  ['Themes', themes.join(', ')],
  ['Button colors', colors.join(', ')],
  ['Icon keys', icons.join(', ')],
])}

The stored \`pen\` icon key renders a conventional pencil. It remains stable for existing settings files. See [data model](data-model.md) for validation and backup rules.

## Resolved dependencies

These versions come from \`package-lock.json\`, not assumptions about what “latest” means.

| Package | Declared range | Locked version | Kind |
| --- | --- | --- | --- |
${rows(
  ['dependencies', 'devDependencies'].flatMap((kind) =>
    Object.entries(pkg[kind])
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([name, range]) => [
        name,
        range,
        lock.packages[`node_modules/${name}`]?.version ?? 'UNRESOLVED',
        kind,
      ]),
  ),
)}
`;
const target = new URL('../docs/reference.md', import.meta.url);
if (process.argv.includes('--check')) {
  let existing = '';
  try {
    existing = readFileSync(target, 'utf8');
  } catch {
    /* Report missing as stale. */
  }
  if (existing !== content) {
    console.error('docs/reference.md is stale. Run npm run docs:generate and review the diff.');
    process.exitCode = 1;
  }
} else {
  writeFileSync(target, content);
  console.log('Updated docs/reference.md');
}
